server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: email-service
          uri: lb://email-service
          predicates:
            - Path=/api/email/**
          filters:
            - StripPrefix=2
            - name: JwtHeaderRelay

        - id: employee-service
          uri: lb://employee-service
          predicates:
            - Path=/api/employee/**
          filters:
            - StripPrefix=2
            - name: JwtHeaderRelay

        - id: application-service
          uri: lb://application-service
          predicates:
            - Path=/api/application/**
          filters:
            - StripPrefix=2
            - name: JwtHeaderRelay

        - id: housing-service
          uri: lb://housing-service
          predicates:
            - Path=/api/housing/**
          filters:
            - StripPrefix=2
            - name: JwtHeaderRelay

        - id: composite-service
          uri: lb://composite-service
          predicates:
            - Path=/api/composite/**
          filters:
            - StripPrefix=2
            - name: JwtHeaderRelay
  security:
    oauth2:
      resourceserver:
        jwt:
          secret: NiXTYNwyutkwyp34w3TYjb297yYUZCaCmr3YhDdT0W4=