app:
  originsUrl: ${FRONTEND_URL:http://localhost:8000}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

springdoc:
  api-docs:
    path: /openapi/api-docs
  swagger-ui:
    path: /swagger-ui
    url: /openapi/api-docs