spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    template:
      exchange: emailExchange
      routing-key: sendEmail
  mail:
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

server:
  port: 8085
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/