server:
  port: 8082

spring:
  application:
    name: employee
  rabbitmq:
    host: ${RABBITMQ_HOST:123131localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
    virtual-host: ${RABBITMQ_VHOST:/}

  data:
    mongodb:
      uri: mongodb://localhost:27017/EmployeeService

app:
  jwt:
    secret: NiXTYNwyutkwyp34w3TYjb297yYUZCaCmr3YhDdT0W4=
  expiration-in-ms: 86400000
  originsUrl: ${FRONTEND_URL:http://localhost:5172}
  
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always