server:
  port: 8082

spring:
  application:
    name: employee

  data:
    mongodb:
      uri: mongodb://localhost:27017/EmployeeService

app:
  jwt:
    secret: NiXTYNwyutkwyp34w3TYjb297yYUZCaCmr3YhDdT0W4=
  expiration-in-ms: 86400000
  originsUrl: http://localhost:5173
  
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always