server:
  port: 8084

spring:
  application:
    name: housing-service

  datasource:
    url: jdbc:mysql://your-rds-endpoint:3306/housing_db
    username: db_user
    password: db_password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

cloud:
  aws:
    credentials:
      accessKey: aws_access_key
      secretKey: aws_secret_key
    region:
      static: us-east-1

custom:
  s3:
    bucket-name: bucket-name

logging:
  level:
    root: INFO
